### ISSUE TITLE
ImportError: libboost_system.so.1.61.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SayantiBardhan** [islamamirul/rsdnet#1]
Hi,

I am running this from AWS Deep Learning AMI. After doing 
1. cmake all caffe-rsdnet
2. Downloading the data and trained model. Setting caffe_root = '/home/ubuntu/rsdnet/caffe-rsdnet/'
On running the command, bash test_rsdnet.sh.
I get the following error:
![rsdnet](https://user-images.githubusercontent.com/40729359/48921383-7133fa80-eec5-11e8-923b-674a05b9a837.png)

I tried multiple time to resolve the issue and I also deleted files and re-imported the file and still get same issues. Assistance would be greatly appreciated.

**Comment by islamamirul** [comment]
Hi,

Did you download and build the caffe-rsdnet first? Make sure you build it first along with pycaffe and change the caffe root in test_rsdnet.py script.

**Comment by SayantiBardhan** [comment]
I was able to solve the previous error, however, I am now getting this error:

Traceback (most recent call last):
  File "./scripts/inference/test_rsdnet.py", line 16, in <module>
    import caffe
  File "/home/ec2-user/src/caffe_python_3/rsdnet/caffe-rsdnet/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ec2-user/src/caffe_python_3/rsdnet/caffe-rsdnet/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe


I have _caffe.cpp in the path ./rsdnet/caffe-rsdnet/python/caffe/
1. Can you let me know how to solve this
2. I might be missing something in the make of caffe-rsdnet. Can you clarify the exact steps of make of this file.
